apiVersion: v1
kind: Service
metadata:
  name: sonarjenkins-service
spec:
  selector:
    app: sonarjenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Changed from NodePort to LoadBalancer