apiVersion: v1
kind: Service
metadata:
  name: sonarjenkins-service
spec:
  selector:
    app: sonarjenkins
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 8080  # Container port
      nodePort: 30080   # External port (must be between 30000â€“32767)
